daquest/daquest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('previous_question/', include('previous_question.urls')),
               path('', include('questions.urls')),
               path('question/', include('questions.urls')),
               path('solution/', include('solution.urls')),
               path('admin/', admin.site.urls),
               ]

if settings.DEBUG:
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

daquest/previous_question/urls.py
from django.urls import path

from . import views

app_name = 'previous_question'

urlpatterns = [
    path('', views.previous_question, name="previous_question"),
]

daquest/questions/urls.py
from django.urls import path

from . import views

app_name = 'question'

urlpatterns = [
    path('', views.index, name='index'),
]

daquest/register/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "register"

urlpatterns = [
    path('', views.signup, name="register"),
]

if settings.DEBUG:
    static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

daquest/solution/urls.py
from django.urls import path

from . import views

app_name = 'solution'

urlpatterns = [
    path('', views.solution, name="solution"),
]

daquest/previous_question/models.py
from django.db import models

# Create your models here.

daquest/questions/models.py
from django.db import models
from django.contrib import admin


class Questions(models.Model):
    question_title = models.TextField(max_length=30, null=False)
    question_text = models.TextField(null=False)
    published_date = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return self.question_title


class Comments(models.Model):
    question = models.ForeignKey(
        Questions, on_delete=models.SET_NULL, null=True)
    author = models.CharField(max_length=30,)
    comment_text = models.CharField(max_length=200)
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_text

class Solutions(models.Model):
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)
    solution_text =  models.TextField()
    published_date_solution = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.solution_text

daquest/register/models.py
from django.db import models

# Create your models here.

daquest/questions/forms.py
from django import forms


class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "author",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "maxlength": "120",
            "rows": "3",
            "cols": "40",
            "class": "comment_body",
            "placeholder": "Maximum 120 Characters"
        })
    )

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].label = "Comment"

daquest/register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field in ['username', 'email', 'password1', 'password2']:
            self.fields[field].help_text = None

daquest/previous_question/views.py
from django.shortcuts import render

from questions.models import Questions, Comments


def previous_question(request):
    questions = Questions.objects.all().order_by('-published_date')
    context = {"questions": questions}
    return render(request, 'question/previous.html', context)

daquest/questions/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404

from .models import Questions, Comments

from .forms import CommentForm

# Get Question and Display


def index(request):

    # Give Latest Question
    latest_question = Questions.objects.latest('published_date')
    context = {"latest_question": latest_question}

    # Get Comments for current question
    comments = Comments.objects.filter(question=latest_question.id)
    context['comments'] = comments
    context['form'] = CommentForm
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comments(
                question=latest_question,
                author=form.cleaned_data["author"],
                comment_text=form.cleaned_data["body"],
            )
            comment.save()
        return HttpResponseRedirect('/')

    return render(request, 'question/index.html', context)

daquest/register/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import cache_page
from .forms import RegisterForm


@cache_page(60 * 15)
@csrf_protect
def signup(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect("/question")
    else:
        form = RegisterForm()
    return render(response, 'question/signup.html', {"form": form})

daquest/solution/views.py
from django.shortcuts import render
from questions.models import Solutions, Questions
#from daquest.questions.models import Solutions, Questions

# Create your views here.


def solution(request):
    latest_question = Questions.objects.latest('published_date')
    solution_text = Solutions.objects.filter(question=latest_question.id)
    context = {'latest_question': latest_question, 'solutions': solution_text}

    return render(request, 'question/solution.html', context)

daquest/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="../static/css/base.css" />
    {% block link_css %}{% endblock link_css %}
    <link
      href="https://fonts.googleapis.com/css?family=Playfair+Display:700&display=swap"
      rel="stylesheet"
    />
    <title>DaQuest{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav>
      <div class="head">
        <h1 class="app_name"><a href="/question">DaQuest</a></h1>
        <a href="{% url 'previous_question:previous_question' %}" class="previous_question">
          <div class="previous_question_div">Previous Questions</div>
        </a>
      </div>
    </nav>

    {% block content %}{% endblock content %}

  </body>
  <footer></footer>

</html>

daquest/templates/question/index.html
{% extends 'base.html' %}

{% block link_css %}
<link rel="stylesheet" href="../static/css/index.css" />
{% endblock link_css %}

{% block content %}
<div class="question_div">
  <h1 class="today_title">Todays Question</h1>
  <p class="underscore">─</p>
  <div class="question_text">
    <p style="font-weight: bold; font-size: 30px; padding-bottom: 30px">{{ latest_question.question_title }}</p>
    <p>
      {% autoescape off %}
        {{ latest_question.question_text|linebreaksbr}}
      {% endautoescape %}
    </p>
  </div>
  <a href="{% url 'solution:solution' %}" class="solution_link">Get Solution</a>
</div>

<div class="comment_form_div">
  <h1>Add Comment</h1>
  <p class="underscore">─</p>
  <form method="post" class="comment_form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="comment_button">COMMENT</button>
  </form>
</div>
<div class="comments">
  <h1>Comments</h1>
  <p class="underscore">─</p>
  <div class="comments_list_div">
  <ul class="comments_list">
  {% for comment in comments  %}
    <li class="comment"><p><b>{{ comment.author }} </b>: {{ comment.comment_text }}</p></li>
    <hr>
  {% endfor %}
  </ul>
</div>

{% endblock content %}

daquest/templates/question/previous.html
{% extends 'base.html' %}

{% block link_css %}
<link rel="stylesheet" href="../static/css/previous_question.css" />
{% endblock link_css %}

{% block content %}
<div class="question_div">
  <h1 class="previous_title">Previous Question</h1>
  <p class="underscore">─</p>
</div>
    {% for question in questions %}
    <div class="question_text">
        <p style="font-size: 25px;padding-bottom: 0;">{{ question.question_title }}</p>
        <p><b>{{ question.published_date }}</b></p>
        <hr style="border: 1px solid rgb(220, 220, 220);">
        <p>
            {% autoescape off %}
                {{ question.question_text|linebreaksbr}}
            {% endautoescape %}
        </p>
  </div>

    {% endfor %}

{% endblock content %}

daquest/templates/question/signup.html
{% extends 'base.html' %}

{% block link_css %}
<link rel="stylesheet" href="../static/css/signup2.css" />
{% endblock link_css %}

{% block title %} | Sign up
{% endblock title %}

{% block content %}
    <form method= "POST" class="form_signup">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn">Sign-up</button>
    </form>
{% endblock content %}

daquest/templates/question/solution.html
{% extends 'base.html' %}

{% block link_css %}
<link rel="stylesheet" href="../static/css/solution2.css" />
{% endblock link_css %}



{% block content %}
<div class="solution_div">
    <h1 class="question_title">{{latest_question.question_title}}</h1>
    <p class="question_text">{{latest_question.question_text|linebreaksbr}}</p>
    <h3 class="solution_title">Solution</h3>
    {% for solution in solutions %}
        <p class="solution_text">{{solution.solution_text|linebreaksbr }}</p>    
    {% endfor %}
</div>
{% endblock content %}